name: Deploy Docfx

on:
  push:
    branches: [main]

jobs:
  generate-docs:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.101
      - name: Remove Examples
        run: dotnet sln FreeKit.sln remove (ls -r samples/**/*.csproj)
      - name: Remove Test
        run:  dotnet sln FreeKit.sln remove (ls -r test/**/*.csproj)
      - name: Install dependencies
        run: dotnet restore FreeKit.sln
      - name: Setup DocFX
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install docfx
      - name: DocFX Build
        working-directory: docs
        run: docfx docfx.json
        continue-on-error: false
      - name: Publish
        if: github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_site
          force_orphan: true
