name: gitee-mirror

on:
  push:
    branches:
      - main
      - gh-pages

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee 💕
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        with:
          source-repo: "git@github.com:luoyunchong/FreeKit.git"
          destination-repo: "git@gitee.com:igeekfan/FreeKit.git"
